### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by behzodhalil** [getspherelabs/anypass-kmp#60]

**Comment by rooparsh** [comment]
Hi, I am getting podFile missing error while trying to build the project. Could you please let me know if this is something you are currently working on ?

Thanks

**Comment by behzodhalil** [comment]
Hi, @rooparsh! Thanks for your interest!


It appears that the missing component is the `authManager` podfile.  Could you please execute the `cleanup` script? Additionally, kindly run `./gradlew podInstall`. But sometimes `podInstall` don't work properly.

Also, to solve this you can navigate to the "iosApp" directory and follow these steps after executing the `cleanup` script:

1. `pod deintegrate`
2. `pod init`
3.  Copy the `pod` modules
4. `pod install`

Following these steps should ensure that everything works smoothly.

Best regards :)

**Comment by rooparsh** [comment]
Hey @behzodhalil , I tried the above mentioned steps; but still getting same error.

Additionally, while trying `pod install` , I am getting `The Podfile does not contain any dependencies.`.

**Comment by behzodhalil** [comment]
Write your `Podfile`:

```
target 'iosApp' do
    use_frameworks!
    platform :ios, '14.1'
    pod 'shared', :path => '../shared'
    pod 'navigation', :path => '../navigation'
    pod 'local', :path => '../data/local'
end
```

**Comment by rooparsh** [comment]
hey @behzodhalil , I tried with above mentioned steps and also tried with news steps mentioned in README.md. 

I am still unable to build the project. If i comment out the ios specific code in gradle files, then I am able to build the android project but then it crashes(haven't debugged the issue yet). 

But with ios specific code in gradle files, I am getting 
`Caused by: java.lang.IllegalStateException: 'pod install' command failed with code 1.`in data, shared and navigation modules.

**Comment by behzodhalil** [comment]
Hi @rooparsh,

1. To run the Android project, you'll need to make your own `google-service.json` file.
2. Do you have a `Podfile`, or are you on an M1 Mac?

**Comment by rooparsh** [comment]
Hey,
I have created a Google-services.json file.

Yes, I do have pod file and I am on m2 pro.

**Comment by behzodhalil** [comment]
@rooparsh 

1. Would you be able to kindly share your error logs while running the Android app?
2. I think, after deleting the Podfile and reinitializing, it should work.

**Comment by rooparsh** [comment]
hey @behzodhalil 
I am able to build the project now. The issue is with ruby and cocoapods version. I followed the youtrack issue [link](https://youtrack.jetbrains.com/issue/KT-49418#focus=Comments-27-5386841.0-0). 

Maybe you can add it in Readme , so that it helps someone trying to setup the project.

**Comment by behzodhalil** [comment]
Hey, @rooparsh 

It's nice to see you solved the building problem. It's already added in `README` file.  You can check it out in third section of `setup`.
